#!/bin/bash
###############################################################################
#@(#) (STATE-JOB) :W: forces the Slurm job to the top of the queue
###############################################################################
function VERSION(){
cat <<\EOF
PRODUCT:        Slurm tools
PROGRAM:        s-top
DESCRIPTION:    forces the Slurm job to the top of the queue
VERSION:        1.0, 2023-12-29
AUTHOR:         John S. Urban
REPORTING BUGS: http://www.urbanjost.altervista.org/
HOME PAGE:      http://www.urbanjost.altervista.org/index.html
LICENSE:        MIT
EOF
}
###############################################################################
# compare before and after values for a job, Priority and Nice changed

#  <    Priority=4294901751 Nice=0
#  ---
#  >    Priority=4294901755 Nice=-4

#trap 'rm -fv $scratch1 $scratch2' EXIT
trap 'rm -f $scratch1 $scratch2' EXIT

scratch1=/tmp/scratch_$(uuidgen).txt
scratch2=/tmp/scratch_$(uuidgen).txt
USER=${USER:-${LOGNAME:-$(logname)}}
#-#MAX=$(squeue --user=${USER} --format=%Q|sort -k 1n|tail -n 1)
#-#MAX=$(( ${MAX:-0} + 1 ))

[ $# == 0 ] && exec echo "$(basename $0): no Slurm jobIDs supplied for which to raise priority" 1 >&2

for JOBID in $*
do
   : Before
   scontrol show JobId=$JOBID --details > $scratch1

   # actually change ( might be restricted to privileged ID)
   scontrol top $JOBID

   : After
   scontrol show JobId=$JOBID --details > $scratch2
   scontrol show JobId=$JOBID --details |grep -i prio

   diff $scratch1 $scratch2

done
###############################################################################
exit
###############################################################################
cat >/dev/null <<\EOF
TODO:  Maybe query if allowed for non-privileged user, but user can apparently
       only decrease priority or nice value

  scontrol update JobId=$JOBID Priority=$MAX
  scontrol update JobId=$JOBID Priority= 4294930591
  scontrol show JobId=$JOBID --details |grep -i prio
  scontrol update JobId=$JOBID Priority=$MAX
  scontrol update JobId=$JOBID nice=$NNN
  top job_list
    Move the specified job IDs to the top of the queue of jobs belonging
    to the identical user ID, partition name, account, and QOS. The
    job_list argument is a comma separated ordered list of job IDs. Any
    job not matching all of those fields will not be effected. Only jobs
    submitted to a single partition will be effected. This operation
    changes the order of jobs by adjusting job nice values.

    The net effect on that user's throughput will be negligible
    to slightly negative. This operation is disabled by default for
    non-privileged (non-operator, admin, SlurmUser, or root) users. This
    operation may be enabled for non-privileged users by the system
    administrator by including the option "enable_user_top" in the
    SchedulerParameters configuration parameter.
EOF
